// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mZVsDBQFzhmpLyh7hbuvgJrr-MJ6Xe8',
    appId: '1:926631975879:web:9e880af5f7ecc94e6857e2',
    messagingSenderId: '926631975879',
    projectId: 'smp-project-361c3',
    authDomain: 'smp-project-361c3.firebaseapp.com',
    storageBucket: 'smp-project-361c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWnXUjUHZZiTxPUwmMhu1UQg_JylAmhI',
    appId: '1:926631975879:android:ca27370f00c8d7a86857e2',
    messagingSenderId: '926631975879',
    projectId: 'smp-project-361c3',
    storageBucket: 'smp-project-361c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Ky54KtWCZ_m2uiDvFX4mf5gOeZNjy3w',
    appId: '1:926631975879:ios:b29ac355a03c42146857e2',
    messagingSenderId: '926631975879',
    projectId: 'smp-project-361c3',
    storageBucket: 'smp-project-361c3.appspot.com',
    iosBundleId: 'com.example.spodApp',
  );
}
